name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
        
    - name: Build
      run: msbuild /p:Configuration=Debug  /t:"restore;clean;build"
      
#     - name: Pack
#       run: msbuild /p:Configuration=Release /t:"pack"
