name: Continuous Integration
on:
  push:
    branches:    
      - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1

      - name: Build
        shell: bash
        run: |
          msbuild /p:Configuration=Debug  /t:"restore;clean;build"
